# Use the official Node.js image as the base image
FROM node:14

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install Node.js dependencies and the Angular CLI
RUN npm install && npm install -g @angular/cli@~14.0.7

# Copy the rest of the application code
COPY . .

# Expose port 80 for the Angular application
EXPOSE 8789

# Command to run the Angular development server
CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "8789"]
